-- AlterTable
ALTER TABLE "GameSession" ALTER COLUMN "playedAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "nextPlayAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Reward" ALTER COLUMN "usedAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3);
