-- AlterTable
ALTER TABLE "GameSession" ALTER COLUMN "playedAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "nextPlayAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Reward" ALTER COLUMN "usedAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMP(3);
